[tools]
darklua = { github = "seaofvoices/darklua", version = "=0.13.1"}
luau-lsp = { github = "JohnnyMorganz/luau-lsp", version = "=1.29.0"}
lune = { github = "lune-org/lune", version = "=0.8.4"}
rojo = { github = "rojo-rbx/rojo", version = "=7.4.1"}
run-in-roblox = { github = "rojo-rbx/run-in-roblox", version = "=0.3.0"}
selene = { github = "Kampfkarren/selene", version = "=0.27.1"}
stylua = { github = "JohnnyMorganz/StyLua", version = "=0.20.0"}
